pipeline {
  agent {
    kubernetes {
      inheritFrom 'deploy-user'
      defaultContainer 'helm'
      namespace 'soa-microservices'
      serviceAccount 'usersoa-deployer'
    }
  }

  environment {
    RELEASE_NAME = 'chatsoa'
    CHART_PATH = 'helm_charts/chat-soa'
    NAMESPACE = 'soa-microservices'
    IMAGE_TAG = "latest"
    DOCKERHUB_USERNAME = 'inestmimi123'
    IMAGE_NAME = 'k-chatsoa'
  }

  stages {
    stage('Helm Upgrade') {
      steps {
        container('helm') {
          script {
            try {
              sh """
                helm upgrade --install ${RELEASE_NAME} ${CHART_PATH} \
                  --namespace ${NAMESPACE} \
                  --set image.repository=${DOCKERHUB_USERNAME}/${IMAGE_NAME} \
                  --set image.tag=${IMAGE_TAG}
              """
            } catch (Exception e) {
              echo "Erreur dans le stage 'Helm Upgrade' : ${e.message}"
              error("Échec du déploiement Helm")
            }
          }
        }
      }
    }
  }

  post {
    success {
      echo "Déploiement réussi pour ChatSOA"
    }
    failure {
      echo "Échec du déploiement pour ChatSOA"
    }
  }
}
