apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradle-cache-chatsoa
  namespace: soa-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-chatsoa
  namespace: soa-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
