credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub-creds"
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_PASSWORD}"
              description: "DockerHub credentials for pushing images"
          - string:
              scope: GLOBAL
              id: "kubernetes-config"
              secret: "${KUBERNETES_CONFIG}"
              description: "Kubernetes config for Minikube"