jenkins:
  systemMessage: "Jenkins configured as Code for SOA Microservices"
  numExecutors: 0
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: "${ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  globalLibraries:
    libraries:
      - name: "soa-shared-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/ines312692/Microservices_Social_Engagement_Architecture.git"
            libraryBranch: "feature/Jenkins_as_Code"
        defaultVersion: "main"
        implicit: true
clouds:
  - kubernetes:
      name: kubernetes
      serverUrl: "https://minikube:8443"
      namespace: "soa-microservices"
      credentialsId: "kubernetes-config"
      skipTlsVerify: true
      maxRequestsPerHost: 32
      templates:
        - name: "build-chat"
          namespace: "soa-microservices"
          label: "build-chat"
          containers:
            - name: "docker"
              image: "docker:24.0.2-dind"
              command: "sleep"
              args: "9999999"
              ttyEnabled: true
              volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: "docker-sock"
                - mountPath: "/mnt/gradle_cache"
                  name: "gradle-cache"
                - mountPath: "/mnt/artifacts"
                  name: "artifacts"
            - name: "gradle"
              image: "gradle:8.6-jdk17"
              command: "sleep"
              args: "9999999"
              ttyEnabled: true
          volumes:
            - hostPathVolume:
                hostPath: "/var/run/docker.sock"
                mountPath: "/var/run/docker.sock"
            - persistentVolumeClaim:
                claimName: "gradle-cache-chatsoa"
                mountPath: "/mnt/gradle_cache"
            - persistentVolumeClaim:
                claimName: "artifacts-chatsoa"
                mountPath: "/mnt/artifacts"
          serviceAccount: "chatsoa-deployer"
        - name: "build-eng"
          namespace: "soa-microservices"
          label: "build-eng"
          containers:
            - name: "docker"
              image: "docker:24.0.2-dind"
              command: "sleep"
              args: "9999999"
              ttyEnabled: true
              volumeMounts:
                - mountPath: "/var/run/docker.sock"
                  name: "docker-sock"
                - mountPath: "/mnt/gradle_cache"
                  name: "gradle-cache"
                - mountPath: "/mnt/artifacts"
                  name: "artifacts"
            - name: "gradle"
              image: "gradle:8.6-jdk17"
              command: "sleep"
              args: "9999999"
              ttyEnabled: true
          volumes:
            - hostPathVolume:
                hostPath: "/var/run/docker.sock"
                mountPath: "/var/run/docker.sock"
            - persistentVolumeClaim:
                claimName: "gradle-cache-engsoa"
                mountPath: "/mnt/gradle_cache"
            - persistentVolumeClaim:
                claimName: "artifacts-engsoa"
                mountPath: "/mnt/artifacts"
          serviceAccount: "engsoa-deployer"