plugins:
  - id: "configuration-as-code"
    version: "latest"
  - id: "git"
    version: "latest"
  - id: "kubernetes"
    version: "latest"
  - id: "docker-workflow"
    version: "latest"
  - id: "credentials"
    version: "latest"
  - id: "credentials-binding"
    version: "latest"
  - id: "pipeline-stage-view"
    version: "latest"
  - id: "helm"
    version: "latest"