apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatsoa-deployment
  namespace: soa-microservices
  labels:
    app: chatsoa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatsoa
  template:
    metadata:
      labels:
        app: chatsoa
    spec:
      containers:
        - name: chatsoa-container
          image: inestmimi123/k-chatsoa:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
