apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatsoa-deployer
  namespace: soa-microservices
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engsoa-deployer
  namespace: soa-microservices
---
