# k8s/tools/sonarqube/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data-pvc
  namespace: soa-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions-pvc
  namespace: soa-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
