replicaCount: 1

image:
  repository: inestmimi123/k-chatsoa
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8082

resources: {}

persistence:
  enabled: true
  artifactClaim: artifacts-chatsoa
