apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
  namespace: soa-microservices
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CASC_JENKINS_CONFIG
              value: {{ .Values.casc.configPath }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: casc-configs
              mountPath: {{ .Values.casc.configPath }}
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
        - name: casc-configs
          configMap:
            name: {{ .Release.Name }}-casc-configs